PACKAGE org.apache.uima;

TYPELIST types = {EXCLAMATION, PERIOD};

DECLARE T1, T2, T3;

ANY+{-PARTOF(PM), -PARTOF(T1) -> MARK(T1,1,2)} PM;
T1{ENDSWITH(PERIOD) -> MARK(T2)};
T1{ENDSWITH(types) -> MARK(T3)};