PACKAGE org.apache.uima;

INT i1;
DOUBLE d1;
BOOLEAN b1;
STRING s1;

DECLARE T1, T2, T3, T4;

NUM{PARSE(i1) -> MARK(T1)};
(NUM PM NUM){PARSE(d1), IF((d1==2.1)) -> MARK(T2)};
W{PARSE(b1), IF(b1) -> MARK(T3)};
ANY+{PARSE(s1), -PARTOF(T4), -PARTOF(SEMICOLON) -> MARK(T4)};