PACKAGE org.apache.uima;

DECLARE T1, T2, T3, T4;

ANY+{-PARTOF(PERIOD), -PARTOF(T1) -> MARK(T1)} PERIOD;
T1{CONTAINS(CW) -> MARK(T2)};
T1{CONTAINS(CW,2,4) -> MARK(T3)};
T1{CONTAINS(CW,25,100,true) -> MARK(T4)};