PACKAGE org.apache.uima;

TYPELIST types = {COMMA, PERIOD, T5};

DECLARE T1, T2, T3, T4, T5, T6;

CW{-> MARK(T5,1,2)} CW{-> MARK(T6)} PERIOD;

ANY{PARTOFNEQ(T5) -> MARK(T1)};
(CW CW){PARTOFNEQ(T5) -> MARK(T2)};
W{PARTOFNEQ(T6) -> MARK(T3)};
ANY{PARTOFNEQ(types) -> MARK(T4)};