PACKAGE org.apache.uima;

DECLARE T1, T2, T3, T4, T5, T6, T7, T8;

Document{ -> RETAINTYPE(SPACE, MARKUP)};
SPACE ANY+{-PARTOF(T1) -> MARK(T1), MARK(T2), MARK(T3)};

T1{-> TRIM(SPACE), TRIM(MARKUP)};
T2{-> TRIM(SPACE, MARKUP)};
T3{-> TRIM({SPACE, MARKUP})};